# Generated by Django 4.1.6 on 2023-03-02 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bug', 'ошибка'), ('Task', 'задача'), ('Enhancement', 'улучшение')], default='Task', max_length=30, verbose_name='Тип')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Время создания')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('status', models.CharField(choices=[('New', 'новый'), ('In process', 'в процессе'), ('Done', 'выполнено')], default='New', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата и время обновления')),
                ('types', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='type', to='tracker_app.type')),
            ],
        ),
    ]
