# Generated by Django 4.1.6 on 2023-03-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0002_alter_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='types',
        ),
        migrations.AddField(
            model_name='issue',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='type', to='tracker_app.type'),
        ),
    ]
