# Generated by Django 4.1.6 on 2023-03-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0003_remove_issue_types_issue_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='type', to='tracker_app.type', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('BUG', 'ошибка'), ('TASK', 'задача'), ('ENHANCEMENT', 'улучшение')], default='TASK', max_length=30, verbose_name='Тип'),
        ),
    ]
